# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actors')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(unique=True, upload_to='cinema_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(default='POINT(49.988358 36.232845)', srid=4326)),
                ('slug', models.SlugField()),
                ('allow_comments', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Area')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_release', models.DateField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('age', models.SmallIntegerField(default=3)),
                ('vertical_image', models.ImageField(unique=True, upload_to='film_images/vertical_images')),
                ('horizontal_image', models.ImageField(unique=True, upload_to='film_images/gorizontal_images')),
                ('big_image', models.ImageField(unique=True, upload_to='film_images/big_images')),
                ('video_url', models.URLField()),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow_comments')),
                ('active', models.BooleanField(default=True)),
                ('cast', models.ManyToManyField(to='cinema_place.Actror')),
            ],
        ),
        migrations.CreateModel(
            name='FilmCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_screening', models.DateField()),
                ('end_screening', models.DateField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produces')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(to='cinema_place.Producer'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='cinema_place.Genre'),
        ),
    ]
