# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
