# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0002_area_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
    ]
