# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0002_auto_20170918_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='name',
            new_name='brand',
        ),
    ]
