# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0003_auto_20171126_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
