# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0003_auto_20170918_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='cinema_pictures')),
            ],
        ),
        migrations.RenameField(
            model_name='filmcinema',
            old_name='name',
            new_name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmpictures',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Film'),
        ),
    ]
