# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0005_auto_20170918_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpictures',
            name='picture',
        ),
        migrations.AddField(
            model_name='filmpictures',
            name='image',
            field=models.ImageField(default='', upload_to='cinema_images'),
            preserve_default=False,
        ),
    ]
