# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0006_auto_20170918_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmPictures',
            new_name='FilmPicture',
        ),
    ]
