# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0007_auto_20170918_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpicture',
            name='image',
            field=models.ImageField(unique=True, upload_to='cinema_images'),
        ),
    ]
