# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_place', '0008_auto_20170918_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmPicture',
            new_name='FilmImage',
        ),
    ]
