# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtest',
            name='some_f',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
