# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('seat', models.SmallIntegerField()),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.CinemaHall')),
            ],
        ),
        migrations.CreateModel(
            name='SeatTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('film_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_place.FilmCinema')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.CinemaHall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_dimensional', models.BooleanField()),
                ('price', models.SmallIntegerField()),
                ('reservation_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.ReservationSeat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.SeatTypes'),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Seat'),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Session'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tickets',
            field=models.ManyToManyField(to='reservation.Ticket'),
        ),
    ]
